import { __makeTemplateObject } from "tslib";
import gql from "graphql-tag";
import { TRANSLATION_PATH_GET_ALL_TRANSLATION, TRANSLATION_PATH_GET_ALL_BY_KEYS, TRANSLATION_PATH_SET_TRANSLATION, TRANSLATION_PATH_EXPORT_TRANSLATION, TRANSLATION_PATH_IMPORT_TRANSLATION, TRANSLATION_PATH_DELETE_TRANSLATION, } from "@wisegar-org/wgo-base-models/build/translation/server";
export var Q_TRANSLATION_GETALL = gql(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  query ($data: GetAllTranslationInput!) {\n    ", "(data: $data) {\n      id\n      key\n      value\n      languageId\n    }\n  }\n"], ["\n  query ($data: GetAllTranslationInput!) {\n    ", "(data: $data) {\n      id\n      key\n      value\n      languageId\n    }\n  }\n"])), TRANSLATION_PATH_GET_ALL_TRANSLATION);
export var Q_TRANSLATION_GETALLBYKEYS = gql(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  query ($data: GetTranslationByKeysInput!) {\n    ", "(data: $data) {\n      id\n      key\n      value\n      languageId\n    }\n  }\n"], ["\n  query ($data: GetTranslationByKeysInput!) {\n    ", "(data: $data) {\n      id\n      key\n      value\n      languageId\n    }\n  }\n"])), TRANSLATION_PATH_GET_ALL_BY_KEYS);
export var M_TRANSLATION_SETTRANSLATION = gql(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  mutation ($data: SetTranslationInput!) {\n    ", "(data: $data) {\n      id\n      key\n      value\n      languageId\n    }\n  }\n"], ["\n  mutation ($data: SetTranslationInput!) {\n    ", "(data: $data) {\n      id\n      key\n      value\n      languageId\n    }\n  }\n"])), TRANSLATION_PATH_SET_TRANSLATION);
export var M_TRANSLATION_DELETE_TRANSLATIONS = gql(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  mutation ($data: DeleteTranslationInput!) {\n    ", "(data: $data)\n  }\n"], ["\n  mutation ($data: DeleteTranslationInput!) {\n    ", "(data: $data)\n  }\n"])), TRANSLATION_PATH_DELETE_TRANSLATION);
export var M_TRANSLATION_INPORT_TRANSLATIONS = gql(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  mutation ($data: ImportTranslationsInput!) {\n    ", "(data: $data)\n  }\n"], ["\n  mutation ($data: ImportTranslationsInput!) {\n    ", "(data: $data)\n  }\n"])), TRANSLATION_PATH_IMPORT_TRANSLATION);
export var Q_TRANSLATION_EXPORT_TRANSLATIONS = gql(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  query ($data: ExportTranslationInput!) {\n    ", "(data: $data)\n  }\n"], ["\n  query ($data: ExportTranslationInput!) {\n    ", "(data: $data)\n  }\n"])), TRANSLATION_PATH_EXPORT_TRANSLATION);
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6;
//# sourceMappingURL=TranslationServiceQueries.js.map