export const LocalStorageSettings = {
  KEY_AUTH_TOKEN: 'AUTH_TOKEN',
  KEY_AUTH_REFRESH_TOKEN: 'AUTH_REFRESH_TOKEN',
  KEY_USER_ID: 'USER_ID',
  KEY_ISSUES_FILTER: 'ISSUES_FILTER',
  KEY_TRANSACTIONS_FILTER: 'TRANSACTIONS_FILTER'
};
