import { __makeTemplateObject } from "tslib";
import gql from "graphql-tag";
import { AUTH_PATH_CHANGE_RESET_PASSWORD, AUTH_PATH_CHECK_USER_NAME, AUTH_PATH_CONFIRM_REGIST, AUTH_PATH_EDIT_USER, AUTH_PATH_LOGIN, AUTH_PATH_ME, AUTH_PATH_REGISTER, AUTH_PATH_RESEND_CONFIRMATION, AUTH_PATH_RESET_PASSWORD, } from "@wisegar-org/wgo-base-models/build/authentication/server";
export var M_AUTH_LOGIN = gql(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  mutation ", "($data: LoginInput!) {\n    ", "(data: $data) {\n      user {\n        id\n        name\n        lastName\n        userName\n        email\n        roles\n        code\n        certificate\n        isEmailConfirmed\n      }\n      token\n    }\n  }\n"], ["\n  mutation ", "($data: LoginInput!) {\n    ", "(data: $data) {\n      user {\n        id\n        name\n        lastName\n        userName\n        email\n        roles\n        code\n        certificate\n        isEmailConfirmed\n      }\n      token\n    }\n  }\n"])), AUTH_PATH_LOGIN, AUTH_PATH_LOGIN);
export var Q_AUTH_ME = gql(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  query ", "($data: MeInput!) {\n    ", "(data: $data) {\n      id\n      name\n      lastName\n      userName\n      email\n      roles\n      code\n      certificate\n      isEmailConfirmed\n    }\n  }\n"], ["\n  query ", "($data: MeInput!) {\n    ", "(data: $data) {\n      id\n      name\n      lastName\n      userName\n      email\n      roles\n      code\n      certificate\n      isEmailConfirmed\n    }\n  }\n"])), AUTH_PATH_ME, AUTH_PATH_ME);
export var M_AUTH_REGISTER = gql(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  mutation ", "($data: RegisterInput!) {\n    ", "(data: $data) {\n      id\n      name\n      lastName\n      userName\n      email\n      roles\n      code\n      certificate\n      isEmailConfirmed\n    }\n  }\n"], ["\n  mutation ", "($data: RegisterInput!) {\n    ", "(data: $data) {\n      id\n      name\n      lastName\n      userName\n      email\n      roles\n      code\n      certificate\n      isEmailConfirmed\n    }\n  }\n"])), AUTH_PATH_REGISTER, AUTH_PATH_REGISTER);
export var M_AUTH_EDIT_USER = gql(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  mutation ", "($data: EditUserInput!) {\n    ", "(data: $data) {\n      id\n      name\n      lastName\n      userName\n      email\n      roles\n      code\n      certificate\n      isEmailConfirmed\n    }\n  }\n"], ["\n  mutation ", "($data: EditUserInput!) {\n    ", "(data: $data) {\n      id\n      name\n      lastName\n      userName\n      email\n      roles\n      code\n      certificate\n      isEmailConfirmed\n    }\n  }\n"])), AUTH_PATH_EDIT_USER, AUTH_PATH_EDIT_USER);
export var M_AUTH_RESEND_CONFIRM = gql(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  mutation ", "($data: ResendConfirmationInput!) {\n    ", "(data: $data)\n  }\n"], ["\n  mutation ", "($data: ResendConfirmationInput!) {\n    ", "(data: $data)\n  }\n"])), AUTH_PATH_RESEND_CONFIRMATION, AUTH_PATH_RESEND_CONFIRMATION);
export var M_AUTH_CONFIRM_REGISTER = gql(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n  mutation ", "($data: MeInput!) {\n    ", "(data: $data)\n  }\n"], ["\n  mutation ", "($data: MeInput!) {\n    ", "(data: $data)\n  }\n"])), AUTH_PATH_CONFIRM_REGIST, AUTH_PATH_CONFIRM_REGIST);
export var M_AUTH_RESET_PASSWORD = gql(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n  mutation ", "($data: ResendConfirmationInput!) {\n    ", "(data: $data)\n  }\n"], ["\n  mutation ", "($data: ResendConfirmationInput!) {\n    ", "(data: $data)\n  }\n"])), AUTH_PATH_RESET_PASSWORD, AUTH_PATH_RESET_PASSWORD);
export var M_AUTH_CHANGE_PASSWORD = gql(templateObject_8 || (templateObject_8 = __makeTemplateObject(["\n  mutation ", "($data: ResetPasswordInput!) {\n    ", "(data: $data)\n  }\n"], ["\n  mutation ", "($data: ResetPasswordInput!) {\n    ", "(data: $data)\n  }\n"])), AUTH_PATH_CHANGE_RESET_PASSWORD, AUTH_PATH_CHANGE_RESET_PASSWORD);
export var Q_AUTH_VALID_USER_NAME = gql(templateObject_9 || (templateObject_9 = __makeTemplateObject(["\n  query ", "($data: ValidUserNameInput!) {\n    ", "(data: $data)\n  }\n"], ["\n  query ", "($data: ValidUserNameInput!) {\n    ", "(data: $data)\n  }\n"])), AUTH_PATH_CHECK_USER_NAME, AUTH_PATH_CHECK_USER_NAME);
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9;
//# sourceMappingURL=AuthServiceQueries.js.map