export const LocalStorageSettings = {
  KEY_AUTH_TOKEN: 'AUTH_TOKEN',
  KEY_ISSUES_FILTER: 'GITHUB_ISSUES_FILTER',
  KEY_TRANSACTIONS_FILTER: 'GITHUB_TRANSACTIONS_FILTER',
  KEY_EXPENSES_FILTER: 'GITHUB_EXPENSES_FILTER',
  KEY_INCOME_FILTER: 'GITHUB_INCOME_FILTER',
  KEY_PRODUCTS_FILTER: 'GITHUB_PRODUCTS_FILTER',
  KEY_BILLS_FILTER: 'GITHUB_BILLS_FILTER'
};
