export const APP_HISTORIC = "APP_HISTORIC";

export const DEFAULT_MESSAGE = "WGO_HISTORIC_DEFAULT_MESSAGE";
export const DEFAULT_CREATE_MESSAGE = "WGO_HISTORIC_DEFAULT_CREATE_MESSAGE";
export const DEFAULT_ACCESS_MESSAGE = "WGO_HISTORIC_DEFAULT_ACCESS_MESSAGE";
export const DEFAULT_EDIT_MESSAGE = "WGO_HISTORIC_DEFAULT_EDIT_MESSAGE";
export const DEFAULT_EDIT_MANY_MESSAGE =
  "WGO_HISTORIC_DEFAULT_EDIT_MANY_MESSAGE";
export const DEFAULT_DELETE_MESSAGE = "WGO_HISTORIC_DEFAULT_DELETE_MESSAGE";
export const DEFAULT_DELETE_SOFT_MESSAGE =
  "WGO_HISTORIC_DEFAULT_DELETE_SOFT_MESSAGE";
export const DEFAULT_RESTORE_MESSAGE = "WGO_HISTORIC_DEFAULT_RESTORE_MESSAGE";
export const WRONG_CREATE_RECORD = "WGO_HISTORIC_WRONG_CREATE_RECORD";
export const WRONG_REGISTER_RECORD = "WGO_HISTORIC_WRONG_REGISTER_RECORD";
export const WRONG_CONTEXT_USER = "WGO_HISTORIC_WRONG_CONTEXT_USER";
export const WRONG_CONTEXT_USER_ID = "WGO_HISTORIC_WRONG_CONTEXT_USER_ID";
export const WRONG_CONTEXT_USER_EMAIL = "WGO_HISTORIC_WRONG_CONTEXT_USER_EMAIL";
export const WRONG_ENTITY_ID_UNDEFINED =
  "WGO_HISTORIC_WRONG_ENTITY_ID_UNDEFINED";

export const historicServerTranslations = [
  DEFAULT_MESSAGE,
  DEFAULT_CREATE_MESSAGE,
  DEFAULT_ACCESS_MESSAGE,

  DEFAULT_EDIT_MESSAGE,
  DEFAULT_EDIT_MANY_MESSAGE,
  DEFAULT_DELETE_MESSAGE,
  DEFAULT_DELETE_SOFT_MESSAGE,
  DEFAULT_RESTORE_MESSAGE,
  WRONG_CREATE_RECORD,
  WRONG_REGISTER_RECORD,
  WRONG_CONTEXT_USER,
  WRONG_CONTEXT_USER_ID,
  WRONG_CONTEXT_USER_EMAIL,
  WRONG_ENTITY_ID_UNDEFINED,
];
